# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"


        name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew test

      # Deploy with Vagrant
      - name: Deploy
        run: nohup java -jar build/libs/spring-petclinic-3.4.0.jar > app.log 2>&1 &

      - name: Upload Artifact (JAR)
        uses: actions/upload-artifact@v2
        with:
          name: petclinic-artifact
          path: build/libs/*.jar