# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Build-Artifacts
        uses: actions/upload-artifact@v3
        path: build/libs/**

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/**
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/**

      - name: Deploy
        run: nohup java -jar build/libs/spring-petclinic-3.4.0.jar > app.log 2>&1 &
