# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      # Install Vagrant for deployment
      - name: Install Vagrant
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant

      #name: Grant execute permission for Gradle Wrapper
      # run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew test

      # Deploy with Vagrant
      - name: Deploy with Vagrant
        run: vagrant up --provision
